### ISSUE TITLE
Ajax null result

### ISSUE THREAD

**Issue by aozfen** [brainfoolong/cryptojs-aes-php#20]
hi, i'm doing the same for example but i can't get any data at all. I use Ajax, so I am having a problem. I am sharing the sample code.

**JS**
`

    var htmlVal = $(".summernote").val()
    var cryptoVal = CryptoJS.AES.encrypt(JSON.stringify(htmlVal), "mysecret", {format: CryptoJSAesJson}).toString();

    $.ajax({
        type: 'POST',
        url: base_url + '/mail/preview',
        data: "json=" + cryptoVal,
        dataType: 'json',
        success: function(e) {
          console.log(e);
        },
    });
`

**PHP**

`echo $this->cryptoJsAesDecrypt("mysecret", $_POST["json"]);`

I am debugging the cryptoJsAesDecrypt method. $ ct value comes smoothly. But it doesn't give back data in openssl section. Openssl active on my server

**Comment by brainfoolong** [comment]
I have a few suggestions
* Use `$.post` instead of `$.ajax` and pass an object like `{'json' : cryptoVal}`. Your parameters of the `$.ajax` call are probably not correct for the case you want
* `$this->cryptoJsAesDecrypt` is not a function from this library, so i cannot give support here. This library use global functions instead of class methods.

**Comment by brainfoolong** [comment]
However, today i've updated the library and examples. Maybe it is more clear now, how to work with this library.

**Comment by aozfen** [comment]
I wrote my own class for Crypto. That's why I called it $this. I pulled out your last commit and used it smoothly
